world_id: world_032
name: New York City, Season 1
language: en
locations:
- id: maclarens_pub
  name: MacLaren's Pub
  connected_to:
  - apartment_4c
  - robin_apartment
  - barneys_apartment
  - liberty_bell
  - metro_news_1
  - lily_kindergarten
  - altru_cell_office
  - eriksen_family_home
  - homeless_shelter
  - wedding_reception
  - high_school_prom
  - new_haven_art_interview
  - carmichaels_restaurant
  - ranjits_limousine
- id: apartment_4c
  name: Apartment 4C
  connected_to:
  - maclarens_pub
  - robin_apartment
  - barneys_apartment
- id: robin_apartment
  name: Robin's Apartment
  connected_to:
  - maclarens_pub
  - apartment_4c
- id: barneys_apartment
  name: Barney's Apartment
  connected_to:
  - maclarens_pub
  - apartment_4c
- id: metro_news_1
  name: Metro News 1
  connected_to:
  - maclarens_pub
- id: lily_kindergarten
  name: Lily's Kindergarten
  connected_to:
  - maclarens_pub
- id: altru_cell_office
  name: AltruCell Office
  connected_to:
  - maclarens_pub
- id: eriksen_family_home
  name: Eriksen Family Home
  connected_to:
  - maclarens_pub
- id: homeless_shelter
  name: Homeless Shelter
  connected_to:
  - maclarens_pub
- id: wedding_reception
  name: Claudia and Stuart's Wedding Reception
  connected_to:
  - maclarens_pub
- id: high_school_prom
  name: High School Prom Venue
  connected_to:
  - maclarens_pub
- id: new_haven_art_interview
  name: New Haven Art Fellowship Interview
  connected_to:
  - maclarens_pub
- id: liberty_bell
  name: Liberty Bell
  connected_to:
  - maclarens_pub
- id: carmichaels_restaurant
  name: Carmichael's Restaurant
  connected_to:
  - maclarens_pub
- id: ranjits_limousine
  name: Ranjit's limousine
  connected_to:
  - maclarens_pub
items:
- id: blue_french_horn
  name: Blue French Horn
  type: object
  portable: true
- id: engagement_ring
  name: Marshall's Engagement Ring
  type: object
  portable: true
- id: pineapple
  name: The Pineapple
  type: object
  portable: true
- id: shannon_tape
  name: Shannon Videotape
  type: media
  portable: true
